### ISSUE TITLE
.cia and .3dsx

### ISSUE THREAD

**Issue by GamesSanti** [Tobi-D7/Craftus-Next#8]
Why no precompiled .cia and .3dsx?

**Comment by Tobi-D7** [comment]
Look at https://github.com/NPI-D7/nightlys

**Comment by Tobi-D7** [comment]
Or at Actions

**Comment by Tobi-D7** [comment]
And Cia is currently not supported cause of an Error on launching.

**Comment by GamesSanti** [comment]
Would recommend posting the .3dsx at craftus-next’s release page and also add a change list to each update, most people downloading your version of craftus wont go into the research and work just to compile.

Also, what error does it give you when launching a .cia?

**Comment by Tobi-D7** [comment]
Well first i need to fix some issues that i  made whyle coding the worldselector shows the old folder xd.
And I need to create a new script to. comompile cia but  im not at my pc now. The release page with changelog is a good idea but im doing that later.

**Comment by Tobi-D7** [comment]
I do most things with Github actions

**Comment by GamesSanti** [comment]
Aight, just remember that most people that are gonna download your version probably wont have no idea on how to use github.

Even when I posted on reddit mine and had the compiled .cia and .3dsx on the release page, some people still asked where the download was.

**Comment by Tobi-D7** [comment]
Xd i have currently only development builds. i think I need to update the redme of the updates page and add "download on own risk. The apps you can download here can always crash and arrent testet" or so xd.
I think the first (more stable) version is 0.6.0 . I hope that cia building works then because I'll add that to Universal-DB.

**Comment by skymz4** [comment]
The Cia Works in Citra
Now Testing on N3DS

**Comment by skymz4** [comment]
3ds works too

**Comment by skymz4** [comment]
The cia and 3dsx at nithtlys should have the fixed world Loader
